[package]
name = "rusty-brew"
version = "0.1.0"
authors = ["Didrik Rokhaug <didrik.rokhaug@gmail.com>"]

[dependencies]
panic-abort = ""
cortex-m-rt = ""
nrf52 = ""
nrf52832-hal = {path = "../nrf52-hal/nrf52832-hal"}
cortex-m = ""
